### PR TITLE
add gravity reliability index notebook

### PR DESCRIPTION
**Pull request by RichardScottOZ**
Hi Leo, I am having a look at this, so thought I would share a la your version.

### CODE REVIEW

**Comment by RichardScottOZ** [comment]
Have to see if some of the blank parts overlapped with 'no use' surveys.

**Comment by leouieda** [comment]
Hi @RichardScottOZ sorry for letting this hang. Merging it into another branch and I'll remove a few things that aren't necessarily applicable to the main repo (didn't want to mess things up on your fork). Thanks for sharing!

**Comment by RichardScottOZ** [comment]
No worries - it was only FYI anyway, in case anything useful.

**Comment by leouieda** [comment]
There definitely was 🙂 Also reminded me that we need to add a way for BlockReduce to generate a grid instead of just points.

**Pull request merged**
