### PR TITLE
Update dataset with the survey ID for each point

### PR DESCRIPTION
**Pull request by leouieda**
In case we want to investigate or extract individual surveys, we need to preserve this information somehow. While I'm at it, I'll also update the sample figures and generate a CSV version as well for people who don't want to deal with netCDF and don't need the metadata. One caveat is that one of the survey files was missing from the server so this compilation is a bit smaller (only a few 100 points).

### CODE REVIEW

**Comment by RichardScottOZ** [comment]
Do you know which one?  I can ask Phil if you like.

**Comment by leouieda** [comment]
The URL is this one: http://dapds00.nci.org.au/thredds/fileServer/iv65/Geoscience_Australia_Geophysics_Reference_Data_Collection/ground_gravity/QLD/point/P200441/P200441-point-gravity.nc

**Comment by leouieda** [comment]
I get those URLs from the metadata so maybe something was updated and the link got broken.

**Comment by RichardScottOZ** [comment]
Right - or possibly decided one was now deprecated or something like that.

**Pull request merged**
